### PR TITLE
Add BlazeGraph.

### PR DESCRIPTION
**Pull request by jbkoh**
I have added BlazeGraph in the benchmark. I followed the structure that the other folders use (minor difference in entrypoint.sh) and it's all working. I have tested on the Notebook file. I failed to run hoddb on my machine as it returns 405 error (not allowed method). I disabled the other databases except rdf3x and blazegraph. In average blazegraph beat rdf3x in all queries. Please accept this pull request. (and probably we should review our querying engine stack? Do we still need HodDB other than its user interface and visualization?)

### CODE REVIEW

**Comment by gtfierro** [comment]
Thanks for the PR!

I definitely agree that we should review the querying engine stack, but with the knowledge that HodDB provides (or will soon provide) some extra features not found in RDF databases such as linking to external resources, graph history, and a permissions model for authorized graph access.

There's a few small things to fix before I can merge this in; I'll have some time later today to go through those

**Comment by gtfierro** [comment]
The 405 error is due to a typo in `Results.ipynb`

It should have 

```python
HOD_SERVER = "http://localhost:47808/api/query"
```

rather than

```python
HOD_SERVER = "http://localhost:47808/query"
```

**Comment by jbkoh** [comment]
OK Thanks! We might need to discuss this in public, could you give me more
details on the following features?
- What do you mean by linking to external resources? Is it giving a link?
- What is graph history? Snapshots of graphs? Or does it track metadata
history of each entity?
- What is the granularity of the permission model?



With regards,
Jason Koh (고 범규)

**Comment by gtfierro** [comment]
Hi Jason:

I finally had the chance to try and run the code. Doesn't look like Blazegraph actually gives me any results;  even from the first VAV enumeration query. Can you take a look at this? Seems the reason its so fast is because it doesn't actually return any results.

**Comment by jbkoh** [comment]
Ugh, I will check this weekend

**Comment by jbkoh** [comment]
Misclicked the close button (can't I rollback?). I will check the above issue and let you know this weekend. Thanks for checking that!

**Comment by jbkoh** [comment]
Hey @gtfierro 
I just updated the pull request to receive correct results. Server URL was incorrect. Now I checked it returns results. I compared with rdf3x and it looks like its performance is similar to HodDB. I'd appreciate if you could accept this pull request and post the full comparison.

Thanks!

**Pull request merged**
